// Generated by https://quicktype.io

export class RegisterDto {
    username!: string;
    email!:    string;
    password!: string;
    code:     string = "UDEMYANDROID";
    
}

// Generated by https://quicktype.io

export interface RegisterResponse {
    token:    string;
    username: string;
    email:    string;
    role:     string;
    photoUrl: string;
    created:  string;
    active:   boolean;
}

